package com.example.ptljdf;

import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.Menu;
import android.view.MenuItem;

import com.example.ptljdf.helpers.SpacesItemDecorator;
import com.example.ptljdf.adapters.ShopRecyclerViewAdapter;
import com.example.ptljdf.entities.ProductObject;

import java.util.ArrayList;
import java.util.List;
public class ShoppingActivity extends AppCompatActivity {
    private static final String TAG = ShoppingActivity.class.getSimpleName();
    private RecyclerView shoppingRecyclerView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_shopping);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
        shoppingRecyclerView = (RecyclerView)findViewById(R.id.product_list);
        GridLayoutManager mGrid = new GridLayoutManager(ShoppingActivity.this, 2);
        shoppingRecyclerView.setLayoutManager(mGrid);
        shoppingRecyclerView.setHasFixedSize(true);
        shoppingRecyclerView.addItemDecoration(new SpacesItemDecorator(2, 12, false));
        ShopRecyclerViewAdapter shopAdapter = new ShopRecyclerViewAdapter(ShoppingActivity.this, getAllProductsOnSale());
        shoppingRecyclerView.setAdapter(shopAdapter);
    }
    private List<ProductObject> getAllProductsOnSale(){
        List<ProductObject> products = new ArrayList<ProductObject>();
        products.add(new ProductObject(1, "Tomato - local - Organically grown, Fresh", R.drawable.to, "It Is Organically Grown And Handpicked From Farm,  Local tomatoes are partly sour and partly sweet and contain many seeds inside which are edible. The red colour present in tomatoes is due to lycopene, an anti-oxidant. ", 35, "500 g", "Fruit"));
        products.add(new ProductObject(1, "Onion - Organically grown, Fresh", R.drawable.on, "It Is Organically Grown And Handpicked From Farm, Onion is a vegetable which is almost like a staple in Indian food. This is also known to be one of the essential ingredients of raw salads. They come in different colours like white, red or yellow and are quite in demand in cold salads and hot soups. You can dice, slice or cut it in rings and put it in burgers and sandwiches. Onions emit a sharp flavour and fragrance once they are fried; it is due to the sulphur compound in the vegetable. Onions are known to have antiseptic, antimicrobial and antibiotic properties which help you to get rid of infections. If a piece of onion is inhaled, it can slow down or stop nose bleeding. Those who have sleeping disorders or insomnia can have a good night sleep if they have an onion every day. Onions also help to improve the functions of the digestive system; because it releases the digestive juices and cures any problem related to digestion. ", 32, "1 kg", "Vegetable"));
        products.add(new ProductObject(1, "Watermelon - Organically grown, Fresh With greenish black to smooth dark green surface, Fresho watermelons are globular in shape and are freshly picked for you directly from our farmers\n" +
                "The juicy, sweet and grainy textured flesh is filled with 12-14% of sugar content, making it a healthy alternative to sugary carbonated drinks. Flesh colour of these watermelons are pink to red with dark brown/black seeds.", R.drawable.wa, "It Is Organically Grown And Handpicked From Farm,", 59, "1 pc - 1.5 - 2.5 kg", "Fruit"));
        products.add(new ProductObject(1, "Amla/Nellikai - Organically grown, Fresh", R.drawable.am, "It Is Organically Grown And Handpicked From Farm,  With light-green, translucent skin, amla/Indian Gooseberries are small, round, crisp and juicy berries with a blend of sour and bitter taste. The flesh is astringent Amla cures sore throat, increases diuretic activity. It reduces blood sugar, boosts immunity.\n" +
                "It slows down aging and good to quench thirst ", 150, "1 kg", "Fruit"));
        products.add(new ProductObject(1, "Carrot - Organically grown, Fresh", R.drawable.ca, "It Is Organically Grown And Handpicked From Farm, \n" +
                "A popular sweet-tasting root vegetable, Carrots are narrow and cone shaped. They have thick, fleshy, deeply colored root, which grows underground, and feathery green leaves that emerge above the ground. While these greens are fresh tasting and slightly bitter, the carrot roots are crunchy textured with a sweet and minty aromatic taste. Fresho brings you the flavour and richness of the finest crispy and juicy carrots that are locally grown and the best of the region. ", 53, "500 g", "Vegetable"));
        products.add(new ProductObject(1, "Potato - Organically grown, Fresh", R.drawable.po, "It Is Organically Grown And Handpicked From Farm,  Potatoes have rich and smooth texture filling, reasonable in calories, non-fattening, and are nutrient dense, which means you obtain many nutrients for the amount of calories they have. It is a superior supply of carbohydrates, dietary fiber and numerous minerals like potassium, copper, iron and magnesium. It is also rich in phytochemical antioxidants like flavonoids, other B vitamins including folate. ", 42, "1 kg", "Vegetable"));
        products.add(new ProductObject(1, "Chilli - Green, - Organically grown, Fresh", R.drawable.ch, "It Is Organically Grown And Handpicked From Farm,  Green chillis are the best kitchen ingredient to bring a dash of spiciness to recipes. The fresh flavour and sharp bite makes them a must in almost all Indian dishes. This particular green chilli variety is big. Rich in dietary fiber. So, it eases digestion. Protects against cancer and stimulates the cooling center of the brain by lowering the body temperature. This is the reason why in a hot place like India, chillies are consumed alot. It also possesses anti-bacterial properties. ", 18, "100 g", "Vegetable"));
        products.add(new ProductObject(1, "Ginger - Organically grown, Fresh", R.drawable.gi, "It Is Organically Grown And Handpicked From Farm,  Firm and fibrous ginger roots are stretched with multiple fingers that have light to dark tan skin and rings on it and is aromatic, spicy and pungent. The flavour gets intensified when the ginger is dried and lessens when cooked. Ginger root treats morning sickness. They reduce muscle pain, soreness and eases various stomach problems.\n" +
                "Drinking ginger juice is a great medicine to relieve sore throats.", 64, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Cucumber - Organically grown, Fresh", R.drawable.cu, "It Is Organically Grown And Handpicked From Farm,  With high water content and crunchy flesh, Cucumbers have striped, light to dark green coloured skin that is edible. Cucumbers keep our body hydrated. Its hard skin has good amount of fiber and minerals. Eating cucumber improves digestion and reduces stress.\n" +
                "It reduces the risk of breast, ovarian, uterine and prostate cancers. The anti-inflammatory compounds in cucumbers help remove waste from the body and reduce skin irritation and it contains anti-wrinkling and anti-ageing", 30, "500 g", "Fruit"));
        products.add(new ProductObject(1, "Garlic - Organically grown, Fresh", R.drawable.ga, "It Is Organically Grown And Handpicked From Farm,  Garlic is made of several heads wrapped in thin whitish layers. They are firm and have a mild flavour. Once crushed, they emit a strong and pungent aroma. Garlic combats sickness, including the common cold and cough. They reduce blood pressure, the risk of heart diseases and kills intestinal worms and harmful bacteria. Additionally garlics improve athletic performance.", 42, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Tomato - hybrid, - Organically grown, Fresh", R.drawable.toh, "It Is Organically Grown And Handpicked From Farm,  Tomato Hybrids are high-quality fruits compared to desi, local tomatoes. They contain numerous edible seeds and are red in colour due to lycopene, an anti-oxidant. Tomatoes contain lycopene, an antioxidant that reduces the risk of cancer and heart-diseases. They protect the eyes from light induced damage.\n" +
                "Essential for pregnant women as these tomatoes protect infants against neural tube defects. ", 50, "1 kg", "Fruit"));
        products.add(new ProductObject(1, "Beetroot - Organically grown, Fresh", R.drawable.be, "It Is Organically Grown And Handpicked From Farm,  These edible ruby red roots are smooth and bulbous and have the highest sugar content than any other vegetable.  Red beets lower blood pressure, promotes brain and heart health. It fights inflammation and boosts energy levels. ", 41, "500 g", "Vegetable"));
        products.add(new ProductObject(1, "Coconut - Organically grown, Fresh", R.drawable.co, "It Is Organically Grown And Handpicked From Farm, \n" +
                "Coconut is a extremely steady fruit. It is a grown-up fruit of the cocos nucifera palm. The fruit is approximately spherical to oval in shape and measure between 5-10 inches in width. Its hard external husk is light green, and turns gray as the nut grown up. The husk is concerning 1-2 inches in thickness and completed of solid fibers ", 32, "1 pc", "Fruit"));
        products.add(new ProductObject(1, "Coccinia - Organically grown, Fresh", R.drawable.coc, "It Is Organically Grown And Handpicked From Farm,  The flesh of Coccinia is crunchy with a mild bitter after taste but the matured ones taste even sweeter. The translucent white flesh with seeds embedded turns red on ripening. They are oval to elongated with thick and light green skin.  Coccinia protects the nervous system and prevents kidney stones. They improve metabolism and reduce fat. It acts as an anti bacterial agent. ", 17, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Beans - Organically grown, Fresh", R.drawable.bea, "It Is Organically Grown And Handpicked From Farm,  Haricot beans are small, oval, plump and creamy-white with a mild flavour and a smooth, buttery texture. Haricot beans are great for metabolism and regulation of the sugar level of blood. They support the adrenal regulation function and provide an excellent source of protein and fibre. A good source of many nutrients and proves to be a healthy diet. ", 88, "500 g", "Vegetable"));
        products.add(new ProductObject(1, "Muskmelon - Organically grown, Fresh", R.drawable.mu, "It Is Organically Grown And Handpicked From Farm,  Muskmelons have cooling properties. They are good for the skin and help in weight loss. Also cures constipation, bladder infections and fatigue.\n" +
                "Folic acid, which is essential for pregnant women to prevent natural defects in the foetus is abundantly present in musk melon. It is a good source of vitamin C, potassium and dietary fiber.\n", 59, "1 pc", "Fruit"));
        products.add(new ProductObject(1, "Pomegranate - Organically grown, Fresh", R.drawable.pom, "It Is Organically Grown And Handpicked From Farm,  Fresho is our brand of fresh fruits and vegetables which are individually handpicked everyday by our experienced and technically competent buyers. Our buying, storing and packaging processes are tailored to ensure that only the fresh, nutrient dense, healthy and delicious produce reaches your doorstep. We guarantee the quality of all Fresho products. If you're not satisfied with the freshness of the items, you can hand them back to our Customer Experience Executive (CEE) for a full refund. Fresh, Sorted & Packed ", 77, "500 g", "Fruit"));
        products.add(new ProductObject(1, "Bottle Gourd - Organically grown, Fresh", R.drawable.bo, "It Is Organically Grown And Handpicked From Farm,  With the common household name 'Lauki', Bottle gourds come in different shapes and sizes. Considered as one of the healthiest vegetables around, the flesh of bottle gourds are full of water and taste slightly bitter.  Bottle gourds keep the body hydrated and assist in weight loss. They treat urinary tract infection and sleeping disorders while reducing liver inflammation, easing digestion and safeguarding hair against premature greying. ", 35, "1 pc", "Vegetable"));
        products.add(new ProductObject(1, "Fresh Turmeric - Organically grown, Fresh", R.drawable.tu, "It Is Organically Grown And Handpicked From Farm,  The best thing about Fresho fresh turmeric is that is pleasantly mild and does not have any sharp taste. The fresh turmeric has a lighter shade of colour than common turmeric. This looks quite similar to ginger, but the taste is earthy and peppery. The fresh turmeric root can be used to lend a yellowish-orange colour to soups or smoothies. ", 15, "250 g", "Spices"));
        products.add(new ProductObject(1, "Pumpkin - Organically grown, Fresh", R.drawable.pu, "It Is Organically Grown And Handpicked From Farm,  Disc' shaped pumpkins with smooth, yellowish orange skin have creamish to orange flesh with a pleasant squash-like taste. Their flat, edible seeds ( pepitas) are tender and mildly sweet. A cup of cubed pumpkin has twice the daily vitamin A content that is essential for good vision. Pumpkins are rich in fiber.\n" +
                "They are also good for male sexual health. Pumpkin seeds contain serotonin, that helps relax and promotes better sleep. ", 56, "1 pc", "Vegetable"));
        products.add(new ProductObject(1, "Aloe Vera - Organically grown, Fresh", R.drawable.al, "It Is Organically Grown And Handpicked From Farm,  Product image shown is for representation purpose only, the actually product may vary based on season, produce & availability. ", 48, "1 pc", "Vegetable"));
        products.add(new ProductObject(1, "Beans - Broad, - Organically grown, Fresh", R.drawable.beabb, "It Is Organically Grown And Handpicked From Farm,  Fresh broad beans have a delicious earthy flavour that fits well with winter cooking. They have kidney shaped curves that are tender and generally consumed with the pods.  Broad Beans are a great source of proteins and carbohydrates. They are also rich in Vitamins A, B1 and B2. ", 58, "500 g", "Vegetable"));
        products.add(new ProductObject(1, "Banana - raw, - Organically grown, Fresh", R.drawable.ba, "It Is Organically Grown And Handpicked From Farm, \n" +
                "Green banana is an unripened yellow banana. It is a superior supply of fiber, minerals, and vitamins and contains a starch. It is rich in vitamin B6, C, fiber & potassium. It performs more like a fiber than a starch. The resistant starch in green bananas has numerous health benefits. ", 20, "250 g", "Fruit"));
        products.add(new ProductObject(1, "Beans - french ring, - Organically grown, Fresh", R.drawable.beaff, "It Is Organically Grown And Handpicked From Farm,  Thin and cylindrical in shape, French Ring beans come with plump notches that enclose the peas inside. Peas are lime green in colour and semi starchy with sweet and grassy flavours.  French Ring Beans are fiber rich, have less calories and also vitamin K rich that is essential for blood clotting and wound healing. They prevent infections. ", 39, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Capsicum - green, - Organically grown, Fresh", R.drawable.cagg, "It Is Organically Grown And Handpicked From Farm,  Leaving a moderately pungent taste on the tongue, Green capsicums, also known as green peppers are bell shaped, medium-sized fruit pods. They have thick and shiny skin with a fleshy texture inside. Green capsicums have powerful antioxidants and anti-inflammatory properties. Rich in Vitamin A, B complex, C and phytonutrients. Relieves pain of bone disorders and has the capacity to relax the repirartory passage. ", 28, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Cauliflower - Organically grown, Fresh", R.drawable.cau, "It Is Organically Grown And Handpicked From Farm, Cauliflower is made up of tightly bound clusters of soft, crumbly, sweet cauliflower florets that form a dense head. Resembling a classic tree, the florets are attached to a central edible white trunk which is firm and tender One serving of cauliflower contains 77 percent of daily recommended value of vitamin C. Cauliflowers are rich in B complex vitamins, potassium and manganese.They protect from the risk of heart diseases and brain disorders. It also contains cancer fighting nutrient called sulforaphane. ", 66, "1 pc", "Vegetable"));
        products.add(new ProductObject(1, "Baby potato - Organically grown, Fresh", R.drawable.pobb, "It Is Organically Grown And Handpicked From Farm, Baby potatoes usually have a soft brown thin external skin with a creamy off white interior. It has a sweeter taste. ", 41, "500 g", "Vegetable"));
        products.add(new ProductObject(1, "Pineapple - Organically grown, Fresh", R.drawable.pi, "It Is Organically Grown And Handpicked From Farm,  With the shape of a pine cone, the fruit is loosely fibrous and juicy with white to yellowish flesh. The edible center part is firm, leathery and sweet. Pineapples reduce the risk of macular degeneration, a disease that affects the eyes as people age due to vitamin C and antioxidants present in it. Reduces inflammation and blood clot. Also reduces common cold and sinus inflammation. Helps develop strong bones. ", 89, "1 pc - 750 - 800 g", "Fruit"));
        products.add(new ProductObject(1, "Beans - cluster, - Organically grown, Fresh", R.drawable.beacc, "It Is Organically Grown And Handpicked From Farm,  These narrow long beans, called Cluster beans or Guar, come with tiny pods and are highly nutritious. Cluster beans are rich in minerals like potassium, folate, Iron and calcium. They are a rich source of vitamins such as A, B and K. Cluster beans and their seeds have enormous medicinal value and are packed with health benefits like decreasing blood sugar levels and cholesterol. ", 19, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Cucumber - malabar, - Organically grown, Fresh", R.drawable.cumm, "It Is Organically Grown And Handpicked From Farm, Fresho Organic products are organically grown and handpicked by expert. These cucumbers are oval shaped and have green and yellow stripes on the outer surface. The inner flesh is juicy with many seeds.  Cucumbers have most of the vitamins that our body needs in a single day. The high water content and dietary fiber in cucumbers are very effective in ridding the body of toxins, thereby aiding digestion. ", 34, "1 kg", "Fruit"));
        products.add(new ProductObject(1, "Capsicum - yellow, - Organically grown, Fresh", R.drawable.cayy, "It Is Organically Grown And Handpicked From Farm,  Leaving a mild fruity flavour on the tastebuds, Yellow capsicums, also known as Yellow bell peppers are bell shaped, medium-sized fruit pods. They have thick and shiny skin with a fleshy texture on the inside. Yellow capsicums have powerful antioxidants and anti-inflammatory properties. Rich in Vitamin A, B complex, C and phytonutrients. Relieves pain of bone disorders and has the capacity to relax the respirartory passage. ", 75, "1 pc", "Vegetable"));
        products.add(new ProductObject(1, "Capsicum - red, - Organically grown, Fresh", R.drawable.car, "It Is Organically Grown And Handpicked From Farm, Red capsicums are thin, smooth skinned, crunchy, mildly sweet tasting, hollow vegetables that are juicier variants of the green capsicum. They are perfect for adding a dash of colour, distinct taste and beautiful scent to your salad, pizza, pasta or even gravy preparations. They are sourced directly from farmers, so that you receive only the best quality ones which not only jazz up any dish but also offer health benefits", 77, "1 pc", "Vegetable"));
        products.add(new ProductObject(1, "Colocasia - Organically grown, Fresh", R.drawable.col, "It Is Organically Grown And Handpicked From Farm,  A stuffy, fleshy underground root, Colocasia is also called 'Taro Root'. It is oval/globular in shape with a hairy coating on its skin and whitish yellow flesh. Colocasias are rich in carbohydrates and dietary fiber. They contain high levels of vitamin A, C, E, vitamin B6, and folate and regulate blood glucose levels, blood pressure, hypertension, and prevent cell damage.", 36, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Neem Giloy (Amruta Balli) - Organically grown, Fresh", R.drawable.ne, "It Is Organically Grown And Handpicked From Farm, Giloy or Guduchi, also known as Amruta balli, is an ayurvedic natural herb, used in several Ayurvedic medicinal preparations. When combined with different types of herbs, it is known to produce alleviating effects on the various doshas defined in Ayurveda. This makes it a very versatile and powerful herb. The bark of Giloy looks greyish brown or creamy white in colour. It often grows on its own, found clinging to huge trees, especially mango and neem. It is generally known to improve the immune system, thereby protecting against infections. ", 22, "100 g", "Vegetable"));
        products.add(new ProductObject(1, "Ladies Finger - Organically grown, Fresh", R.drawable.la, "It Is Organically Grown And Handpicked From Farm,  Ladies finger is a green vegetable with a tip at the end and a lighter green head, which is inedibe and to be thrown away. It tastes mild and slightly grassy.  Ladies finger aids in digestion as it contains prebiotic fiber and controls obesity and cholesterol.", 34, "500 g", "Vegetable"));
        products.add(new ProductObject(1, "Cabbage - Organically grown, Fresh", R.drawable.cab, "It Is Organically Grown And Handpicked From Farm,  With a texture of crispness and juiciness the moment you take the first bite, cabbages are sweet and grassy flavoured with dense and smooth leafy layers. Cabbage improves brain health and vision. Best for people who want to lose weight in a healthy way. It detoxifies the body and contains glutamine that reduces effects of inflammation, allergies, joint pain, irritation, fever. Cabbages also help prevent cancer. ", 27, "1 pc", "Vegetable"));
        products.add(new ProductObject(1, "Lemon - Organically grown, Fresh", R.drawable.le, "It Is Organically Grown And Handpicked From Farm,  With a segmented flesh that has a unique pleasant aroma and a strong sour taste, lemons are round/oval and have a yellow, texturized external peel.  Lemon promotes hydration and keeps the skin healthy. They help ease digestion, prevents kidney stones and freshens breath. Lemons are a very good source of Vitamin C.", 48, "4 pc", "Fruit"));
        products.add(new ProductObject(1, "Sweet Lime - Organically grown, Fresh", R.drawable.sw, "It Is Organically Grown And Handpicked From Farm, Sweet lime or mosambi is lime-like, large sized with an underlying yellow base. The intense, refreshing aroma is due to essential oils present in the skin. It generally tastes sweet, occasionally tart to sweet. Mosambis are a good source of vitamin C and potassium and its high water content is known for its cooling properties. They lower cholesterol and control blood sugar level. They also prevent constipation. Mosambi peels are highly nutritious, fiber-rich and edible, which are good for skin and nails. ", 68, "500 g", "Fruit"));
        products.add(new ProductObject(1, "Sambar Onion - Organically grown, Fresh", R.drawable.sa, "It Is Organically Grown And Handpicked From Farm,  Also known as button onions, Sambar Onions are relatively smaller onions with a mild flavour and slightly sweet taste. Sambar Onions contain high amounts of fibre and flavonoids. They can heal infections and reduces inflammation.\n" +
                "They also have antioxidant properties that help prevent cancer and digestive or heart diseases. ", 25, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Banana Flower - Organically grown, Fresh", R.drawable.baff, "It Is Organically Grown And Handpicked From Farm, \n" +
                "Banana flower, also known as banana blossom, is a tear-shaped maroon or purplish flower hanging at the end of banana clusters grows on the end of the stem holding a cluster of bananas. The edible flower has a unique and excellent taste rich in nutrients. With every purple outer sheath removed it has anthers which are edible.  Banana blossoms reduce menstrual bleeding. They help reduce diabetes and anemia and are a rich source of vitamins and minerals. ", 16, "1 pc", "Fruit"));
        products.add(new ProductObject(1, "Mango alphonso (Ratnagiri) - Organically grown, Fresh", R.drawable.ma, "It Is Organically Grown And Handpicked From Farm, Alphonso Mango is premium quality mango in terms of sweetness, richness and flavour. It is generally referred to as Hapus/Hapoos in Maharashtra and Gujarat. Its a rich source of phytochemicals, Vitamin A & C (those are good antioxidants), Vitamin B and traces of Vitamin E & K. It also contains minerals such as Iron, copper & potassium. Alphonso pulp is used to make jams, jellies, sweets, candies, smoothies and mango drinks", 552, "6 pc", "Fruit"));
        products.add(new ProductObject(1, "Bitter Gourd - Organically grown, Fresh", R.drawable.bi, "It Is Organically Grown And Handpicked From Farm,  The most bitter among all fruits, bitter gourds come with a rough, bumpy and green skin. The off-white translucent flesh tastes crispy with the combination of the bitter seeds that are present inside.  Bitter gourd helps to overcome Type-2 Diabetes and heals liver problems. It clears acne, builds immunity, eases digestion, cures constipation and helps in weight loss. It prevents cancer cells from multiplying, purifies blood and has healing qualities. ", 35, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Coriander leaves - Organically grown, Fresh", R.drawable.cor, "It Is Organically Grown And Handpicked From Farm, Coriander leaves are green, fragile with a decorative appearance. They contain minimal aroma and have a spicy sweet taste. Now do not bother wasting time cutting off the roots as we value your money and time and provide you the freshest leafy edible parts .  Coriander leaves fight food poisoning and lower blood sugar levels. They relieve urinary tract infections and help in maintaining a healthy menstrual cycle while preventing neurological inflammations and diseases. ", 87.50, "250 g", "Greens"));
        products.add(new ProductObject(1, "Curry leaves - Organically grown, Fresh", R.drawable.curr, "It Is Organically Grown And Handpicked From Farm,  With dark green and glossy appearance, curry leaves have a strong flavour and release a tasty aroma when fried in hot oil.  Curry leaves are anti-diabetic and anti-carcinogenic.They help in the better functioning of the heart. they are a good remedy for diarrhea, nausea and indigestion. Curry leaves help improve eyesight and prevents cataract.", 8, "100 g", "Greens"));
        products.add(new ProductObject(1, "Celery - Organically grown, Fresh", R.drawable.ce, "It Is Organically Grown And Handpicked From Farm, Relish juicy, crunchy and mildly salty flavoured celeries that are individually handpicked everyday by our trained farmers. Celeries have wide, green leaves attached to thick, juicy stalks joined at a common base.  Celeries being a low energy vegetable makes it a good and healthy option for people on diets. Celery juice aids in healthy bowel movements, treats arthritis pain and detoxifies the whole body. ", 17.50, "250 g", "Vegetable"));
        products.add(new ProductObject(1, "Pea eggplant/sundaikai - Organically grown, Fresh", R.drawable.pe, "It Is Organically Grown And Handpicked From Farm,  Pea sized light green fruits are bitter to tart when raw with a crunchy texture owing to the flat brown edible seeds inside. Once cooked, they turn soft and the bitter flavour is minimized.  Pea egg plants are loaded with calcium, iron and vitamins like A and B complex. They are rich in dietary fiber and have a high water content. ", 15, "100 g", "Vegetable"));
        products.add(new ProductObject(1, "Raw mango - Organically grown, Fresh", R.drawable.ra, "It Is Organically Grown And Handpicked From Farm,\"Raw mango is a sweet-smelling fruit which is liked by al for its tart flavor. The colour varies in shades of greens and the inner flesh is white in colour " +
                " Its potent health benefits makes totapuri mango puree concentrate - an important food item. It is very rich in Vitamin C. They also have trace amounts of Vitamin B, K and E. ", 39, "1 kg", "Fruit"));
        products.add(new ProductObject(1, "Broccoli - Organically grown, Fresh", R.drawable.br, "It Is Organically Grown And Handpicked From Farm,  With a shape resembling that of a cauliflower, Brocollis have clusters of small, tight flower heads. These heads turn bright green on cooking and tastes slightly bitter.  Broccoli prevents cancer and reduces cholesterol. Maintains bone and heart health. Good for skin, eyes and has anti-ageing properties. ", 95, "500 g", "Vegetable"));
        products.add(new ProductObject(1, "Sweet Corn - Organically grown, Fresh", R.drawable.swee, " It Is Organically Grown And Handpicked From Farm, Wrapped in lime coloured husks with silk, sweet corn contains numerous yellow succulent kernels that have a starchy and doughy consistency. The skin pops out as you bite into it", 14, "1 pc", "Vegetable"));
        return products;
    }
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {

        int id = item.getItemId();
        if (id == R.id.action_bar_title) {
            Intent intent = new Intent(this, Main2Activity.class);
            startActivity(intent);
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
}